// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "OI.h"
#include "SmartDashboard/SmartDashboard.h"

#include "Commands/ShootOnce.h"
#include "Commands/TMonter.h"
#include "Commands/Viser.h"

#include "Commands/Pilotage.h"
#include "Commands/Avancer.h"
#include "Commands/Tourner.h"
#include "Commands/Shoot.h"
#include "Commands/SafeSpin.h"
#include "Commands/StopShoot.h"

#include "Commands/MonterBalle.h"

#include "Commands/OpenTreuilServo.h"
#include "Commands/CloseTreuilServo.h"

OI::OI() {

    stick.reset(new Joystick(0));
    gamepad.reset(new Joystick(1));

    bouton1.reset(new JoystickButton(stick.get(), 1));
    //bouton1->ToggleWhenPressed(new Viser());
    
    bouton2.reset(new JoystickButton(stick.get(), 2));
    bouton2->ToggleWhenPressed(new MonterBalle());


    bouton3.reset(new JoystickButton(stick.get(), 3));
    bouton3->ToggleWhenPressed(new Viser());
/*
    bouton4.reset(new JoystickButton(stick.get(), 4));
    bouton4->WhenPressed(new StopShoot());

    bouton5.reset(new JoystickButton(stick.get(), 5));
    bouton5->WhenPressed(new Shoot());
*/
    //bouton6.reset(new JoystickButton(stick.get(), 6));
    //bouton6->ToggleWhenPressed(new MonterBalle());

    bouton9.reset(new JoystickButton(stick.get(), 9));
    bouton9->WhenPressed(new OpenTreuilServo());

    bouton10.reset(new JoystickButton(stick.get(), 10));
    bouton10->WhenPressed(new CloseTreuilServo());

    bouton11.reset(new JoystickButton(stick.get(), 11));
    bouton11->WhileHeld(new TMonter());

    gboutonA.reset(new JoystickButton(gamepad.get(), 1));
    gboutonA->WhenPressed(new SafeSpin());

    gboutonB.reset(new JoystickButton(gamepad.get(), 2));
    gboutonB->WhenPressed(new Shoot());

    gboutonX.reset(new JoystickButton(gamepad.get(), 3));
    gboutonX->WhenPressed(new StopShoot());

    //SmartDashboard::PutData("Pilotage", new Pilotage());
    //SmartDashboard::PutData("Avancer", new Avancer());
    //SmartDashboard::PutData("Tourner", new Tourner());
    //SmartDashboard::PutData(frc::Scheduler::GetInstance());

}


std::shared_ptr<Joystick> OI::getStick() {
   return stick;
}

